ArkProjectNFTs/ark-project

Cargo.lock, crates/pontos/Cargo.toml, crates/pontos/src/lib.rs, crates/pontos/src/managers/block_manager.rs, crates/pontos/src/managers/token_manager.rs, crates/pontos/src/storage/types.rs, examples/pontos.rs, examples/pontos_pending.rs
This pull request introduces significant changes to our application's indexer version management. Here's a summary of the key changes made:
1. **Conversion of Indexer Version from `u64` to `String`**:
- We have modified the data type of the indexer version from `u64` to `String`, allowing for more flexible version representation.
2. **Integration of Version Comparison Dependency**:
- We have incorporated the `version-compare` dependency to facilitate version comparison operations within the `should_skip_indexing` (previously `check_candidate`) method.
These changes enhance the versatility and accuracy of our indexer version management, providing better compatibility with various version formats and enabling more robust version comparison. This improvement enhances the overall reliability …
=> feat(pontos): upgrade indexer version handling

crates/pontos/src/storage/types.rs
This PR addresses changes in the string representation of `EventType` and `ContractType` enums.
1. **EventType Display Changes**:
- `Mint`: Changed from "🟢 Mint" to "MINT"
- `Burn`: Changed from "🔴 Burn" to "BURN"
- `Transfer`: Changed from "🔵 Transfer" to "TRANSFER"
- `Uninitialized`: Changed from "❓ Uninitialized" to "UNINITIALIZED"
2. **ContractType ToString Changes**:
- `Other`: Changed from "other" to "OTHER"
- `ERC721`: Remains "ERC721"
- `ERC1155`: Remains "ERC1155"
3. **ContractType FromStr Changes**:
- Updated to recognize "ERC721" and "ERC1155" in uppercase.
=> fix(types): Update Storage Types for Token & Event

crates/pontos/src/lib.rs, crates/pontos/src/managers/collection_manager.rs, crates/pontos/src/managers/contract_manager.rs, crates/pontos/src/managers/mod.rs, crates/pontos/src/managers/token_manager.rs, crates/pontos/src/storage/mod.rs, crates/pontos/src/storage/types.rs, examples/pontos.rs, examples/pontos_pending.rs
BREAKING CHANGES: types and function signature were changed.
Ensure that storage exposed types are starknet agnostic, for a better
storage implementation in clients.
Also rename `collection` into `contract` for consistency across the project.
=> refactor(pontos)!: refacto exposed types to be starknet independant

crates/ark-starknet/src/format.rs, crates/pontos/src/lib.rs, crates/pontos/src/managers/contract_manager.rs, crates/pontos/src/storage/types.rs
Errors was not displayed correctly, only a `En error occurred`.
Now the `IndexerError` are displayed correctly.
=> fix(pontos): indexer error message is now displayed correctly

crates/ark-starknet/src/client/http.rs, crates/ark-starknet/src/client/mod.rs, crates/pontos/src/lib.rs, crates/pontos/src/managers/event_manager.rs
It fixes the indexing error that occurs with the pending blocks:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }', 
``` 
- Fixes #135 will close issue 135 when the PR is merged.
=> fix(pontos): filter and process only transfer-related events

crates/pontos/src/storage/types.rs
Include the 'requested' status in the Indexer Status enumeration, which is currently missing.
=> feat(pontos): add requested indexer status

Cargo.lock, crates/ark-starknet/Cargo.toml, crates/ark-starknet/src/lib.rs
Add the from_hex_be function to the CairoU256 struct to enable creating a CairoU256 from a hexadecimal value.
=> feat(ark-starknet): add `from_hex_be` fn to `CairoU256`

Cargo.lock, crates/ark-metadata/Cargo.toml, crates/ark-metadata/src/file_manager.rs, crates/ark-metadata/src/metadata_manager.rs, crates/ark-metadata/src/utils.rs
Replace the use of the lib library with tracing to facilitate tracing of debug messages.
=> fix(ark-metadata): use tracing

Cargo.lock, crates/ark-metadata/Cargo.toml, crates/ark-metadata/src/metadata_manager.rs, crates/ark-metadata/src/storage.rs, crates/ark-metadata/src/types.rs, crates/ark-metadata/src/utils.rs, crates/ark-starknet/Cargo.toml
Add a missing function to the ark-metadata storage and rename the struct for Image Cache Options.
=> fix(ark-metadata): add missing `find_token_ids_without_metadata` function

crates/ark-metadata/src/metadata_manager.rs, crates/ark-metadata/src/storage.rs
This pull request enhances the metadata_manager function definitions to enable the retrieval of tokens without metadata. Additionally, it introduces an optional filter for contract_address, allowing for more flexible token retrieval.
+
It fixes a bug related to `get_token_uri` function
=> fix(ark-metadata): refresh token metadata

Cargo.lock, Cargo.toml, crates/ark-starknet/Cargo.toml, crates/ark-starknet/src/client/http.rs, crates/ark-starknet/src/client/mod.rs
Currently, `starknet-rs` is changing some low provider stuff. But also, it's slow to have PR merged.
For this concern, this PR fixes the contract identification by providing
a separate branch that implement the correct behavior for `starknet-rs` when a contract
error occurs.
We can now effectively detect `EntrypointNotFound` contract error.
=> fix: update starknet to 0.7.0 and fix contract error entrypoint not found

crates/ark-metadata/src/file_manager.rs, crates/ark-metadata/src/metadata_manager.rs
This update modifies the 'save' method within the ark-metadata package. Upon successfully uploading a file to S3, the method now returns the URL of the stored file, providing immediate access to the file's location. This streamlines the process by which clients can retrieve and utilize their stored data.
=> fix(ark-metadata): save function returns the media file localisation

crates/ark-contracts/arkchain/src/order/order_v1.cairo, crates/ark-contracts/arkchain/src/order/types.cairo, crates/ark-contracts/arkchain/src/orderbook.cairo, crates/ark-contracts/arkchain/tests/common/setup.cairo, crates/ark-contracts/arkchain/tests/common/signer.cairo, crates/ark-contracts/arkchain/tests/integration/test_create_listing_order.cairo, crates/ark-contracts/arkchain/tests/integration/test_fulfill_listing.cairo, crates/ark-contracts/arkchain/tests/lib.cairo, crates/ark-contracts/arkchain/tests/unit/test_orderbook.cairo, scripts/signature/src/index.ts, scripts/signature/src/types.ts, scripts/signature/src/utils.ts
This pull request introduces significant updates to the `Orderbook` contract, focusing on the implementation of listing order fulfillment and the enhancement of testing scenarios.
1. **Fulfilling Listing Order Functionality:**
- A new function, `fulfill_order`, has been added to handle the process of fulfilling orders. This function takes in `execution_info` and `signer` as parameters and follows these steps:
- Verifies the signer.
- Validates the existence of the order and its status.
- Checks if the order is open and not fulfilled by the same offerer.
- Distinguishes the order type and proceeds with the fulfillment process for listing orders.
2. **Private Function for Listing Order Fulfillment:**
- The `_fulfill_listing_order` private function has been implemented to specifically handle …
=> feat(listing): add fulfill listing & tests

Cargo.lock, Cargo.toml, artifacts/orderbook.json, crates/ark-starknet/src/client/http.rs, crates/diri/Cargo.toml, crates/diri/artifacts/orderbook.json, crates/diri/src/lib.rs, crates/diri/src/orderbook.rs, crates/diri/src/storage/types.rs
Bump starknet-rs to last stable version 0.8.0.
Rework the contract error handling accordingly.
=> feat: bump starknet-rs and re-work contract error accordingly

crates/solis/messaging.local.json, packages/deployer/README.md
=> docs(readme): deployer readme update

contracts/ark_common/src/protocol/order_types.cairo, contracts/ark_orderbook/README.md, contracts/ark_orderbook/src/broker/database.cairo, contracts/ark_orderbook/src/lib.cairo, contracts/ark_orderbook/src/order/order_v1.cairo, contracts/ark_orderbook/src/orderbook.cairo, contracts/ark_orderbook/src/orderbook_event_mock.cairo, contracts/ark_orderbook/tests/common/setup.cairo, contracts/ark_orderbook/tests/integration/test_cancel_order.cairo, contracts/ark_orderbook/tests/integration/test_create_auction_offers.cairo, contracts/ark_orderbook/tests/integration/test_create_listing_order.cairo, contracts/ark_orderbook/tests/integration/test_fulfill_auction.cairo, contracts/ark_orderbook/tests/integration/test_fulfill_listing.cairo, contracts/ark_orderbook/tests/integration/test_fulfill_offers.cairo, contracts/ark_orderbook/tests/unit/order/test_order_v1.cairo
add a way to whitelist brokers & test if they are authorized to create, fulfill an order.
=> feat(ark-orderbook): whitelist brokers

.changeset/slimy-bananas-mate.md, packages/core/examples/cancelListing.ts, packages/core/jest.config.ts, packages/core/package.json, packages/core/src/contracts.ts, packages/core/tests-new/cancel.test.ts, pnpm-lock.yaml
Switch tests for Jest instead of mocha 
https://github.com/ArkProjectNFTs/ark-project/pull/304
Update all the core SDK tests with jest
=> test(sdk-core): use jest instead of mocha

.github/workflows/arkproject-rs.yml, Cargo.lock, contracts/Scarb.toml, contracts/ark_common/src/protocol/order_types.cairo, contracts/ark_orderbook/Scarb.toml, contracts/ark_orderbook/src/orderbook.cairo, contracts/ark_starknet/Scarb.toml, contracts/ark_starknet/src/executor.cairo, crates/ark-metadata/Cargo.toml, crates/diri/Cargo.toml, crates/diri/src/orderbook.rs, crates/diri/src/storage/types.rs, rust-toolchain.toml
1. Update `orderbook::OrderExecuted` event with the following data:
```cairo
#[derive(Drop, starknet::Event)]
struct OrderExecuted {
#[key]
order_hash: felt252,
#[key]
order_status: OrderStatus,
version: u8,
transaction_hash: felt252,
from: ContractAddress,
to: ContractAddress,
}
```
2. Update diri to handle `OrderExecuted` version 0 and version 1
=> feat(orderbook): implement new executed event

contracts/ark_starknet/src/executor.cairo, contracts/ark_starknet/src/interfaces.cairo, contracts/ark_starknet/tests/integration/fees_amount.cairo, contracts/ark_starknet/tests/lib.cairo
Add `get_fees_amount` to retrieve fees for a given token:
```cairo
struct FeesAmount {
fulfill_broker: u256,
listing_broker: u256,
ark: u256,
creator: u256,
}
fn get_fees_amount(
self: @T,
fulfill_broker: ContractAddress,
listing_broker: ContractAddress,
nft_address: ContractAddress,
nft_token_id: u256,
payment_amount: u256
) -> FeesAmount;
```
=> feat(executor): add `get_fees_amount` view 

contracts/ark_starknet/src/executor.cairo, contracts/ark_starknet/src/interfaces.cairo, contracts/ark_starknet/tests/integration/create_order.cairo, contracts/ark_starknet/tests/integration/execute_order.cairo, contracts/ark_starknet/tests/integration/fulfill_order.cairo, contracts/ark_starknet/tests/integration/maintenance.cairo, contracts/ark_starknet/tests/lib.cairo
Add support for maintenance mode, when `executor` is disabled, the following functions will revert:
- `create_order`
- `cancel_order`
- `execute_order`
- `fulfill_order`
Here is the interface for maintenance mode:
```cairo
#[starknet::interface]
trait IMaintenance<T> {
fn is_enabled(self: @T) -> bool;
fn enable(ref self: T, enable: bool);
}
```
`IMaintenance::enable` can only be invoked by `admin`
=> feat(starknet): add support for maintenance mode

crates/ark-metadata/src/metadata_manager.rs, crates/ark-metadata/src/types.rs, crates/ark-metadata/src/utils.rs
This pull request adds support for handling non-standard metadata structures in our application. Previously, the code assumed that all metadata followed a standard format with specific fields such as trait_type and value. However, some metadata structures differ, using fields like trait instead of trait_type.
=> fix(ark-metadata): handle non-standard metadata

crates/ark-metadata/src/metadata_manager.rs, crates/ark-metadata/src/utils.rs
Some Loot Survivor collections have on-chain metadata with an invalid JSON structure. A workaround is required to normalize the JSON.
=> feat(ark-metadata): normalize onchain data for loot survivor collections

contracts/ark_starknet/src/executor.cairo, contracts/ark_starknet/tests/integration/cancel_order.cairo, contracts/ark_starknet/tests/lib.cairo
Add check in `cancel_order` to ensure:
- caller is the canceller
- canceller is the offerer
=> fix(contracts): ensure caller is canceller & canceler is the offerer

crates/sana/src/storage/sqlx/default_storage.rs
1. reset listing fields on transfer event
=> fix(sana): reset listing fields on transfer event

packages/core/src/actions/order/cancel.ts, packages/core/src/actions/order/createAuction.ts, packages/core/src/actions/order/createListing.ts, packages/core/src/actions/order/createOffer.ts, packages/core/src/actions/order/fulfillAuction.ts, packages/core/src/actions/order/fulfillListing.ts, packages/core/src/actions/order/fulfillOffer.ts, packages/core/tests/cancelAuction.test.ts, packages/core/tests/cancelListing.test.ts, packages/core/tests/cancelOffer.test.ts, packages/core/tests/createAuction.test.ts, packages/core/tests/createListing.test.ts, packages/core/tests/createOffer.test.ts, packages/core/tests/fulfillAuction.test.ts, packages/core/tests/fulfillListing.test.ts, packages/core/tests/fulfillOffer.test.ts, packages/core/tests/utils/index.ts
Simplify core function and react hooks parameters.
Before:
```ts
const orderHash = await createOffer(config, {
starknetAccount: buyer,
offer: {
brokerId: accounts.listingBroker.address,
tokenAddress: STARKNET_NFT_ADDRESS,
tokenId,
startAmount: BigInt(10)
},
approveInfo: {
currencyAddress: config.starknetCurrencyContract,
amount: BigInt(10)
}
});
```
After:
```ts
const { orderHash } = await createOffer(config, {
account: buyer,
brokerAddress: accounts.listingBroker.address,
currencyAddress: config.starknetCurrencyContract,
tokenAddress,
tokenId,
amount: BigInt(10)
});
```
- Your PR title will be used …
=> feat(core): simplify core action parameters

packages/core/scripts/contracts-check.ts, packages/core/src/actions/account/account.ts, packages/core/src/actions/fees/setArkFees.ts, packages/core/src/actions/fees/setBrokerFees.ts, packages/core/src/actions/fees/setCollectionCreatorFees.ts, packages/core/src/actions/fees/setDefaultCreatorFees.ts, packages/core/src/actions/order/createAuction.ts, packages/core/src/actions/order/createCollectionOffer.ts, packages/core/src/actions/order/createListing.ts, packages/core/src/actions/order/createOffer.ts, packages/core/src/actions/read/getAllowance.ts, packages/core/src/actions/read/getNFTOwner.ts, packages/core/src/actions/read/getOrder.ts, packages/core/src/actions/read/getOrderHash.ts, packages/core/src/actions/read/getOrderSigner.ts, packages/core/src/actions/read/getOrderStatus.ts, packages/core/src/actions/read/getOrderType.ts, packages/core/src/createConfig.ts, packages/core/src/errors/account.ts, packages/core/src/errors/actions.ts, packages/core/src/errors/base.ts, packages/core/src/errors/config.ts, packages/core/src/types/utils.ts, packages/core/src/utils/utils.ts, packages/core/tests/setBrokerFees.test.ts, packages/core/tests/utils/index.ts
This PR adds custom error handling to this project by defining several new error types. These errors are defined in the packages/core/src/errors directory.
Fixes #468
=> feat: add custom errors

contracts/ark_component/src/orderbook/orderbook.cairo, contracts/ark_starknet/tests/integration/create_order.cairo, packages/core/src/actions/order/fulfillAuction.ts, packages/core/src/actions/order/fulfillListing.ts, packages/core/src/actions/order/fulfillOffer.ts, packages/core/src/types/index.ts, packages/core/tests/fulfillAuction.test.ts, packages/core/tests/fulfillListing.test.ts, packages/core/tests/fulfillOffer.test.ts, packages/deployer/src/contracts/erc721royalties.ts
- Add missing emit of `OrderCancelled` event when an order is cancelled by a new one.
- Fix local deployment
- SDK: add missing `quantity` field in `FulfillInfo`
=> fix: emit OrderCancelled event when an order is cancelled by a new one

crates/orderbook/src/events/order_placed.rs, crates/orderbook/src/lib.rs
Add public enums for `OrderType` and `RouteType`
=> feat: expose types required by orderbook indexer
