ArkProjectNFTs/ark-project

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
This PR adds new issue and PR templates to streamline and standardize the contribution process. The templates will guide contributors to provide necessary information when reporting bugs, suggesting features, or submitting PRs.
N/A
Ensure that the templates appear correctly when opening new issues or PRs.
---
N/A
=> chore(github-templates): add issue templates

Cargo.lock, Cargo.toml, crates/ark-metadata/Cargo.toml, crates/ark-metadata/src/metadata_manager.rs, crates/ark-metadata/src/types.rs, crates/ark-metadata/src/utils.rs
Resolved an issue with metadata request and serialization.
=> fix(ark-metadata): save raw_metadata

crates/pontos/src/event_handler.rs, crates/pontos/src/lib.rs, examples/pontos.rs
Add the `on_indexation_range_completed` event handler to identify when block range indexing concludes.
=> feat(pontos): add on_indexation_range_completed event handler

Cargo.lock, Cargo.toml, crates/ark-starknet/Cargo.toml, crates/ark-starknet/src/client/http.rs, crates/ark-starknet/src/client/mod.rs, crates/pontos/Cargo.toml, crates/pontos/README.md, crates/pontos/src/lib.rs, crates/pontos/src/managers/block_manager.rs, crates/pontos/src/managers/contract_manager.rs, crates/pontos/src/managers/event_manager.rs, crates/pontos/src/managers/token_manager.rs, crates/pontos/src/storage/mod.rs, crates/pontos/src/storage/sqlx/default_storage.rs, crates/pontos/src/storage/sqlx/migrations/0_default.sql, crates/pontos/src/storage/sqlx/mod.rs, crates/pontos/src/storage/sqlx/types.rs, crates/pontos/src/storage/types.rs, examples/migrations/0_default.sql, examples/pontos_sqlx.rs
This PR focus on preparing testing locally with Katana for pontos.
The feature also comes with some refacto like:
1. Logs are now less verbose
2. Better error handling to have information of low level error at top level
3. Better contract identification for ERC721 and ERC1155
4. Add some documentation
closes #149
closes #115
closes #150
=> feat: add sqlx for pontos testing rework error and contract identification

Cargo.lock, crates/ark-metadata/Cargo.toml, crates/ark-metadata/src/metadata_manager.rs, crates/ark-metadata/src/types.rs, crates/ark-metadata/src/utils.rs, examples/pontos_sqlx.rs
- Introduce `metadata_updated_at` timestamp to record the last modification time in the Metadata property.
- Implement compatibility for the `glb` file format.
- Ensure graceful handling and avoid panicking when unable to upload files to S3.
=> feat(ark-metadata): add metadata_updated_at

crates/pontos/src/lib.rs
There was a bug in the calculation of the indexing percentage for a range
=> fix(pontos): progress value

crates/ark-metadata/src/storage.rs
Update the metadata storage trait by introducing `update_token_metadata_status` function for enhanced management of metadata error status updates.
=> feat(ark-metadata): add update_token_metadata_status

crates/ark-contracts/arkchain/src/order/order_v1.cairo, crates/ark-contracts/arkchain/src/order/types.cairo, crates/ark-contracts/arkchain/src/orderbook.cairo, crates/ark-contracts/arkchain/tests/lib.cairo, crates/ark-contracts/arkchain/tests/order/test_order.cairo, crates/ark-contracts/arkchain/tests/order/test_order_type.cairo
=> feat(ordertype): add ordertype & route matching + tests

.github/workflows/scarb.yml, crates/ark-contracts/arkchain/src/orderbook.cairo
=> feat(ci): add scarb ci

crates/ark-contracts/arkchain/src/order/order_v1.cairo, crates/ark-contracts/arkchain/src/order/types.cairo, crates/ark-contracts/arkchain/src/orderbook.cairo
=> feat(ressource-hard): add function to get the ressource hash

crates/pontos/src/lib.rs, crates/pontos/src/managers/contract_manager.rs
Fix mistake on contract identification.
=> fix: do not try to deserialize string for contract identification

crates/ark-contracts/arkchain/src/crypto/hash.cairo, crates/ark-contracts/arkchain/src/crypto/signer.cairo, crates/ark-contracts/arkchain/src/order/types.cairo, crates/ark-contracts/arkchain/src/orderbook.cairo, crates/ark-contracts/arkchain/tests/common/setup.cairo, crates/ark-contracts/arkchain/tests/integration/test_cancel_order.cairo, crates/ark-contracts/arkchain/tests/integration/test_create_auction_offers.cairo, crates/ark-contracts/arkchain/tests/integration/test_create_listing_order.cairo, crates/ark-contracts/arkchain/tests/integration/test_fulfill_listing.cairo, crates/ark-contracts/arkchain/tests/lib.cairo, crates/ark-contracts/arkchain/tests/unit/test_orderbook.cairo
=> feat(ark-contracts): add unit tests

crates/ark-contracts/arkchain/src/orderbook.cairo, crates/ark-contracts/arkchain/tests/common/setup.cairo, crates/ark-contracts/arkchain/tests/common/signer.cairo, crates/ark-contracts/arkchain/tests/integration/test_cancel_order.cairo, crates/ark-contracts/arkchain/tests/integration/test_create_auction_offers.cairo, crates/ark-contracts/arkchain/tests/integration/test_create_listing_order.cairo, crates/ark-contracts/arkchain/tests/integration/test_fulfill_auction.cairo, crates/ark-contracts/arkchain/tests/integration/test_fulfill_listing.cairo, crates/ark-contracts/arkchain/tests/lib.cairo, crates/ark-contracts/arkchain/tests/unit/test_orderbook.cairo
=> fix(auction): fulfill auctions

crates/ark-contracts/arkchain/src/orderbook.cairo, crates/ark-contracts/arkchain/tests/common/setup.cairo, crates/ark-contracts/arkchain/tests/integration/test_fulfill_offers.cairo, crates/ark-contracts/arkchain/tests/lib.cairo, crates/ark-contracts/arkchain/tests/unit/test_orderbook.cairo, crates/pontos/src/lib.rs
Fulfill offers (token & collection offers from "classic" order)
=> feat(ark-contracts): fulfill classic offers

Cargo.lock, crates/solis/Cargo.toml, crates/solis/src/args.rs, crates/solis/src/contracts/account.rs, crates/solis/src/contracts/orderbook.rs, crates/solis/src/hooker.rs, crates/solis/src/main.rs, crates/solis/src/solis_args.rs
Add support for new endpoints on Katana to set addresses for Solis.
=> feat: implement new hook to set addresses

Cargo.lock, crates/solis/Cargo.toml, crates/solis/src/args.rs
=> feat: bump katana

crates/diri/Cargo.toml
just remove a useless dependency
=> Diri: remove mongo dependency

crates/ark-metadata/src/types.rs, crates/ark-metadata/src/utils.rs
Create a new metadata property awaiting_metadata_update to indicate that the metadata is currently being refreshed.
=> feat(ark-metadata): add `awaiting_metadata_update`

Cargo.lock, crates/solis/Cargo.toml, crates/solis/src/args.rs, crates/solis/src/hooker.rs, crates/solis/src/main.rs
New version of dojo with the most notable change:
`--db-dir` option to use a persistent database.
=> feat: bump solis with new dojo version

apps/example/src/app/marketplace/assets/[contract_address]/[token_id]/components/asset-infos.tsx, apps/example/src/app/marketplace/assets/[contract_address]/[token_id]/components/asset.tsx, apps/example/src/app/marketplace/assets/[contract_address]/[token_id]/page.tsx, apps/example/src/app/marketplace/explore/components/columns.tsx, apps/example/src/app/marketplace/explore/components/explore.tsx, apps/example/src/types/index.ts
=> fix(assets-infos): add top bid to explore page

apps/example/package.json, apps/example/src/app/examples/components/Cancel.tsx, apps/example/src/app/examples/components/CreateListing.tsx, apps/example/src/app/examples/components/FulfillListing.tsx, apps/example/src/app/examples/components/FulfillOffer.tsx, apps/example/src/app/examples/page.tsx, apps/example/src/app/marketplace/components/main-nav.tsx, apps/example/src/app/marketplace/explore/components/data-table-column-header.tsx, apps/example/src/app/marketplace/explore/components/data-table-pagination.tsx, apps/example/src/app/marketplace/layout.tsx, apps/example/src/components/page-header.tsx, package.json, packages/core/src/contracts.ts, packages/deployer/package.json, turbo.json
=> fix(build): update to fix build & functions changes

crates/ark-metadata/src/byte_array.rs, crates/ark-metadata/src/cairo_string_parser.rs, crates/ark-metadata/src/lib.rs
Decode token URI long strings using Cairo byte arrays
=> feat(ark-metadata): byte array compatibility

Cargo.lock, crates/ark-starknet/Cargo.toml, crates/pontos/Cargo.toml, crates/pontos/src/event_handler.rs, crates/pontos/src/lib.rs, crates/pontos/src/managers/event_manager.rs, crates/pontos/src/managers/token_manager.rs, crates/pontos/src/storage/mod.rs, crates/pontos/src/storage/sqlx/default_storage.rs, crates/pontos/src/storage/types.rs
Index sale events from element contract (nft marketplace).
=> feat(pontos): index sale events from element marketplace

.changeset/odd-crews-clean.md, .changeset/thirty-apes-sing.md, packages/core/examples/createListing.ts, packages/core/examples/fulfillListing.ts, packages/core/examples/fulfillOffer.ts, packages/core/tests/fulfillListing.test.ts, packages/core/tests/fulfillOffer.test.ts
Pass tokenId to approveERC721 (as required by new implementation).
=> fix(sdk): approve erc721 with tokenId

.changeset/stupid-planets-decide.md, packages/react/src/hooks/useCancel.ts
Fix react SDK, update useCancel to use useBurner instead of directly declaring a new account
=> fix(sdk): fix react sdk cancel not using useArkAccount

.github/workflows/arkproject-deploy-contracts-mainnet.yml
Add missing secret env for solis rpc call to set address
=> ci: fix-missing secrets for rpc call

.changeset/tidy-pumpkins-perform.md, apps/example/src/app/marketplace/explore/components/columns.tsx, apps/example/src/app/marketplace/explore/utils/index.ts, apps/example/src/components/media.tsx, apps/example/src/components/starknet-provider.tsx, apps/example/src/components/ui/resizable.tsx, packages/core/examples/cancelAuction.ts, packages/core/examples/cancelListing.ts, packages/core/examples/config/index.ts, packages/core/examples/createAccount.ts, packages/core/examples/createAuction.ts, packages/core/examples/createBroker.ts, packages/core/examples/createListing.ts, packages/core/examples/createOffer.ts, packages/core/examples/fulfillAuction.ts, packages/core/examples/fulfillListing.ts, packages/core/examples/fulfillOffer.ts, packages/core/examples/sendMessageToAppchain.ts, packages/core/examples/utils/changeTokenOwner.ts, packages/core/examples/utils/getBalance.ts, packages/core/examples/utils/getTokenOwner.ts, packages/core/examples/utils/mintERC20.ts, packages/core/examples/utils/mintERC721.ts, packages/core/examples/utils/setArkFees.ts, packages/core/examples/utils/setBrokerFees.ts, packages/core/examples/utils/whitelistBroker.ts, packages/core/package.json, packages/core/src/contracts.ts, packages/core/tsconfig.build.json, pnpm-lock.yaml
- Fixed lint warning for all ts packages/apps
- Fix all examples import for esm/modules
- Build examples
- Fixed build export to support src path
=> fix(sdk): fix examples import + add build

contracts/ark_starknet/src/executor.cairo, contracts/ark_starknet/tests/integration/fulfill_order.cairo
- For auction order, fulfiller and offerer could be the same.
- Renamed some tests
- For auction order, fulfill allowance is check for related order offerer.
=> fix(contracts): allow fulfiller to be the offerer in case of the auction

.changeset/green-carpets-crash.md, contracts.json, examples/core/config/index.ts, examples/core/createBroker.ts, package.json, packages/core/src/constants.ts, packages/core/src/contracts.ts, packages/deployer/package.json, packages/deployer/src/deployStarknetFreemintNft.ts, turbo.json
=> feat(deployer): update for sepolia

crates/solis/src/args.rs, crates/solis/src/hooker.rs
1. add a way to save address in a json file
2. retrieve json file addresses if state is empty (when katana is restarted)
=> feat(hooker): generate json file with addresses

README.md
=> Add missing setup step for env vars

contracts/ark_common/src/protocol/order_database.cairo, contracts/ark_common/src/protocol/order_types.cairo, contracts/ark_common/src/protocol/order_v1.cairo, contracts/ark_orderbook/src/orderbook.cairo, contracts/ark_orderbook/tests/common/setup.cairo, contracts/ark_orderbook/tests/integration/test_cancel_order.cairo, contracts/ark_orderbook/tests/integration/test_create_auction_offers.cairo, contracts/ark_orderbook/tests/integration/test_create_listing_order.cairo, contracts/ark_orderbook/tests/integration/test_fulfill_auction.cairo, contracts/ark_orderbook/tests/integration/test_fulfill_listing.cairo, contracts/ark_orderbook/tests/integration/test_fulfill_offers.cairo, contracts/ark_orderbook/tests/unit/order/test_order_v1.cairo, examples/core/getOrderHash.ts, packages/core/src/actions/order/createAuction.ts, packages/core/src/actions/order/createListing.ts, packages/core/src/actions/order/createOffer.ts
=> feat(start-date): remove start date rules as its not needed anymore

crates/ark-metadata/src/metadata_manager.rs, crates/sana/src/storage/sqlx/default_storage.rs
Update sql query to fix token ownership
=> fix(sana): token ownership

crates/ark-metadata/src/elasticsearch_manager.rs, crates/ark-metadata/src/metadata_manager.rs
1. make elasticsearch optionnal
=> fix(ark-metadata): make elasticsearch optionnal

.changeset/shiny-cows-sing.md, packages/core/src/actions/order/createAuction.ts, packages/core/src/actions/order/createListing.ts, packages/core/src/actions/order/createOffer.ts, packages/core/tests/createAuction.test.ts, packages/core/tests/createListing.test.ts, packages/core/tests/createOffer.test.ts
Use optional offer currency address param if provided.
=> fix(core): use optional offer currency address param

packages/core/jest.config.ts, packages/core/tests/createAccount.test.ts, packages/core/tests/createAuction.test.ts, packages/core/tests/createConfig.test.ts, packages/core/tests/createListing.test.ts, packages/core/tests/createOffer.test.ts, packages/core/tests/fulfillAuction.test.ts, packages/core/tests/fulfillListing.test.ts, packages/core/tests/fulfillOffer.test.ts, packages/core/tests/setBrokerFees.test.ts, packages/core/tests/utils/index.ts
- update broken tests
- remove timeouts
=> refactor(core): update tests

packages/core/tests/setup.ts
Allow tests to be run in project root.
=> test(core): update test env path

crates/sana/src/storage/sqlx/default_storage.rs
=> feat(sana): store price when saving a sale event

apps/docs/src/app/api-guide/page.mdx, apps/docs/src/app/authentication/page.mdx
=> fix(docs): typos

crates/diri/src/storage/types.rs
1. change currency_chain_id format 
=> feat(diri): update currency_chain_id format

apps/docs/src/app/sdk-react/use-cancel/page.mdx, apps/docs/src/app/sdk-react/use-config/page.mdx, apps/docs/src/app/sdk-react/use-create-auction/page.mdx, apps/docs/src/app/sdk-react/use-create-listing/page.mdx
Hello
I fixed some minor spelling issues, in order to ensure a better understanding.
Br, Elias.
=> docs fix spelling issues

Cargo.lock, Cargo.toml, crates/diri/Cargo.toml, crates/diri/src/lib.rs, crates/diri/src/mod.rs, crates/diri/src/storage/types.rs, crates/orderbook/Cargo.toml, crates/orderbook/src/events/common.rs, crates/orderbook/src/events/mod.rs, crates/orderbook/src/events/order_cancelled.rs, crates/orderbook/src/events/order_executed.rs, crates/orderbook/src/events/order_fulfilled.rs, crates/orderbook/src/events/order_placed.rs, crates/orderbook/src/events/rollback_status.rs, crates/orderbook/src/lib.rs, src/lib.rs
- Create `orderbook` package to handle smart contract event parsing.
- Remove unused crates from Cargo.toml
=> feat(diri): split diri orderbook event in another package

.changeset/smooth-bottles-work.md, packages/react/package.json, pnpm-lock.yaml
Use starknet-react latest version.
=> feat(react): use starknet-react v3

Cargo.lock, Cargo.toml, crates/pontos/Cargo.toml, crates/sana/Cargo.toml
1 - bump sqlx librairy to 0.8.2
=> chore(lib): bump sqlx to 0.8.2

contracts/ark_orderbook/src/orderbook.cairo, contracts/ark_orderbook/tests/unit/test_orderbook.cairo, crates/solis/src/hooker.rs
1. Add `reset_order_status` in orderbook
2. Fix call to`rollback_status` in`on_starknet_tx_failed`
=> feat: add `reset_order_status` in orderbook

crates/diri/src/lib.rs
Add block number sorting to ensure that events handling respect temporal order.
=> fix(diri): ensure events are handled sorted by block number

crates/diri/src/lib.rs
1. Process all events of a block even in case of handler failure
2. 
=> fix(diri): try to handle all events of a block even in case of handler failure
